# Python Basic Prog 8

> Q. Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np

def add_matrics(mat1,mat2):
    return np.add(mat1,mat2)

def main():
    row=int(input("enter the no. of rows: "))
    col=int(input("enter the no. of columns: "))
    mat1=np.zeros((row,col))
    mat2=np.zeros((row,col))
    
    for i in range(row):
        for j in range(col):
            mat1[i][j]=int(input(f"enter the element of [{i},{j}]: "))
    for i in range(row):
        for j in range(col):
            mat2[i][j]=int(input(f"enter the number of [{i},{j}]: "))
    
    result=add_matrics(mat1,mat2)
    print(result)
    
if __name__ =="__main__":
    main()



enter the no. of rows: 3
enter the no. of columns: 3
enter the element of [0,0]: 1
enter the element of [0,1]: 2
enter the element of [0,2]: 3
enter the element of [1,0]: 4
enter the element of [1,1]: 5
enter the element of [1,2]: 6
enter the element of [2,0]: 7
enter the element of [2,1]: 8
enter the element of [2,2]: 9
enter the number of [0,0]: 9
enter the number of [0,1]: 8
enter the number of [0,2]: 7
enter the number of [1,0]: 6
enter the number of [1,1]: 5
enter the number of [1,2]: 4
enter the number of [2,0]: 3
enter the number of [2,1]: 2
enter the number of [2,2]: 1
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


> Q. Write a Python Program to Multiply Two Matrices?

In [6]:
def multy_matrics(mat1,mat2):
    return np.dot(mat1,mat2)


row1=int(input("enter the no. of rows of matrix 1: "))
col1=int(input("enter the no. of columns of matrix 1: "))

row2=int(input("enter the no. of rows of matrix 2: "))
col2=int(input("enter the no. of columns of matrix 2: "))

if col1 != row2:
    print("Matrix Multiplication is not possible")
    
else:
    mat1=np.zeros((row1,col1))
    mat2=np.zeros((row2,col2))

    for i in range(row1):
        for j in range(col1):
            mat1[i][j]=int(input(f"enter the element of [{i},{j}]: "))
    for i in range(row2):
        for j in range(col2):
            mat2[i][j]=int(input(f"enter the number of [{i},{j}]: "))

                
result=multy_matrics(mat1,mat2)
print(result)

enter the no. of rows of matrix 1: 2
enter the no. of columns of matrix 1: 3
enter the no. of rows of matrix 2: 3
enter the no. of columns of matrix 2: 2
enter the element of [0,0]: 1
enter the element of [0,1]: 2
enter the element of [0,2]: 3
enter the element of [1,0]: 4
enter the element of [1,1]: 5
enter the element of [1,2]: 6
enter the number of [0,0]: 1
enter the number of [0,1]: 2
enter the number of [1,0]: 3
enter the number of [1,1]: 4
enter the number of [2,0]: 5
enter the number of [2,1]: 6
[[22. 28.]
 [49. 64.]]


> Q. Write a Python Program to Transpose a Matrix?

In [16]:

def transpose():
    row=int(input("enter the no. of rows: "))
    col=int(input("enter the no. of columns: "))
    mat=np.zeros((row,col))


    for i in range(row):
        for j in range(col):
            mat[i][j]=int(input(f"enter the element of [{i},{j}]: "))
    print(mat)
    return np.transpose(mat)

a=transpose()
print("The transposed matrix is:")
print(a)

enter the no. of rows: 2
enter the no. of columns: 2
enter the element of [0,0]: 1
enter the element of [0,1]: 2
enter the element of [1,0]: 3
enter the element of [1,1]: 4
[[1. 2.]
 [3. 4.]]
The transposed matrix is:
[[1. 3.]
 [2. 4.]]


> Q. Write a Python Program to Sort Words in Alphabetic Order?

In [17]:
def sort_words_alphabetically(words):
    return sorted(words)

input_str = input("Enter words separated by spaces: ")
words_list = input_str.split()

sorted_words = sort_words_alphabetically(words_list)

print("Words in alphabetical order:")
for word in sorted_words:
    print(word)

Enter words separated by spaces: amit madhu saswat akash
Words in alphabetical order:
akash
amit
madhu
saswat


> Q. Write a Python Program to Remove Punctuation From a String?

In [18]:
import string

def remove_punctuation(text):
    punctuation = string.punctuation
    return ''.join(ch for ch in text if ch not in punctuation)


if __name__ == "__main__":
    text = "This is a string with, punctuation."
    cleaned_text = remove_punctuation(text)
    print("The cleaned text is:")
    print(cleaned_text)

The cleaned text is:
This is a string with punctuation
